name = "FixedPointToolkit"
uuid = "081f7a28-ac82-48c1-a10e-fa8b3349a52a"
authors = ["Anjishnu Bose <anjishnubose98@gmail.com>", "Samuel Vadnais <samuel.vadnais@utoronto.ca>"]
version = "1.0.1"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
JLD2 = "^0.4"
Logging = "^1.6.7"
Plots = "^1.38"
julia = "^1.7, ^1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
